### ISSUE TITLE
log没有换行，可读性差

### ISSUE THREAD

**Issue by wangdahua28** [jianbing/utx#1]
`_logger_handler.setFormatter(logging.Formatter('%(asctime)s %(message)s' + '\n'))`

建议增加换行
\utx-0.0.2-py3.6.egg\utx\log.py
line：13

**Comment by whw845293102** [comment]
utx-master\build\lib\utx\log.py中添加“\n”换行就可以了

def info(msg):
    _logger.info(Fore.GREEN + "INFO " + str(msg) + Style.RESET_ALL + "\n")

def error(msg):
    _logger.error(Fore.RED + "ERROR " + str(msg) + Style.RESET_ALL + "\n")

def warn(msg):
    _logger.warning(Fore.YELLOW + "WARNING " + str(msg) + Style.RESET_ALL + "\n")

然后在重新安装utx
