### ISSUE TITLE
您好，对于case中调用其它case这种方式执行起来有些问题，没有想到解决思路，麻烦帮忙看一下，谢谢。

### ISSUE THREAD

**Issue by wangdahua28** [jianbing/utx#4]
![image](https://user-images.githubusercontent.com/32984334/54592575-a0b7d580-4a67-11e9-8b3f-2e8d4aa806ee.png)

**Comment by jianbing** [comment]
报这个错是因为用例排序功能将函数名字修改了，如果不需要排序功能的话
setting.sort_case = False
可以解决这个报错

**Comment by wangdahua28** [comment]
谢谢~
