### ISSUE TITLE
你好，我从0.02版本更新到现在的0.0.5版本后，一直会提示报错，麻烦看下是什么原因呢

### ISSUE THREAD

**Issue by zhuxuxg** [jianbing/utx#6]
报错如下，感觉像是report文件夹 没有打包到 utx-0.0.5-py3.6.egg里去，运行你的demo也会报这个错
![image](https://user-images.githubusercontent.com/50005635/56782272-fd51a180-6818-11e9-8659-989b7eaa9249.png)

**Comment by jianbing** [comment]
感谢提交bug，已修复~
